### ISSUE TITLE
Feature request: swipe right to go forward in browsing history

### ISSUE THREAD

**Issue by denniskb** [GrapheneOS/Vanadium#124]
Currently, swiping in from the left screen edge goes back in history. Swiping in from the right does the same. The latter should go forward in history instead. You can provide an option in the settings to switch the two gestures for left-handed people. Thank you!

**Comment by r3g-5z** [comment]
This would deviate from the system gesture navigation settings and standard practice with gesture navigation on all Pixels at the minimum. The current behaviour is how it is on all other applications and it would be unusual to create a special case for the browser.

**Comment by thestinger** [comment]
Chromium used to provide this and disabled it due to the system gestures. It's unfortunate that there isn't a system forward gesture but that's the way it is. They could potentially add it in the future but most apps wouldn't support it and there would need to be configuration for which side is which.

**Comment by stevenae** [comment]
Worth noting that this works (swipe forward as backwards) if you use 3-button (not gesture) os navigation.
