### ISSUE TITLE
Implement native Android Autofill w/Bromite patch

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/Vanadium#132]
uazo and csagan5 have agreed to allow using their implement native autofill patch to be used under the MIT licence.

Native autofill would definitely help a lot of people using Vanadium be able to _less_ rely on using accessibility services for autofill.

https://github.com/bromite/bromite/discussions/1571

https://github.com/bromite/bromite/blob/master/build/patches/Enable-native-Android-autofill.patch

uazo said the patch isn't actually fully complete as native autofill is still present in Incognito browsing without user approval.

**Comment by uazo** [comment]
> I'm curious though, why are the arguments here:
https://github.com/bromite/bromite/blob/master/build/patches/Enable-native-Android-autofill.patch#L848,L849
are the other way around (the last two lines), compared to the other lines changed using that function?
See: https://github.com/bromite/bromite/blob/master/build/patches/Enable-native-Android-autofill.patch#L359,L366

good catch!
from what I had seen, the webview already supports the native android autofill without having to change anything, instead in the browser I have to force it, here is the reason.

>Also, is there any particular reason 2 DCHECKS are used here?
https://github.com/bromite/bromite/blob/master/build/patches/Enable-native-Android-autofill.patch#L353,L355

simply because it is here
https://source.chromium.org/chromium/chromium/src/+/main:weblayer/browser/tab_impl.cc;l=1379;drc=404e8d654e8b26336d2cb103b9c21faecbf7f73a

**Comment by Zanthed** [comment]
@quh4gko8 ^

**Comment by GGORG0** [comment]
Any updates on this? For now I have to use Bitwarden's draw-over autofill which doesn't detect the current website.

**Comment by Morpheus0x** [comment]
Yes, it is quite annoying that some recent update broke autofill (from bitwarden in my case) for websites in vanadium. Is there any progress update on this?

**Comment by thestinger** [comment]
That's a Bitwarden issue. not a Vanadium one.

**Comment by Morpheus0x** [comment]
> That's a Bitwarden issue. not a Vanadium one.

I don't think it's a Bitwarden issue since autofill works everywhere else (any app login, Firefox, Bromite) and this issue specifically describes a problem with vanadium autofill. I am currently using the latest bitwarden (2022.11.0) and both vanadium and bromite on version 108.0, bromite works but vanadium doesn't (up to date Pixel 6). I also tested this with my old Pixel 5 with latest bitwarden and vanadium 106.0 where autofill also works.

**Comment by thestinger** [comment]
Chromium only supports the Play services autofill API, not the native Android one not portable to older OS versions which is why they did it that way. It does work fine in Vanadium. If you're talking about using Bitwarden's accessibility services instead, then that's not relevant, since that's only about the autofill API.

Bitwarden hard-wires a list of supported browsers for their accessibility service and doesn't list app.vanadium.browser so users on a new GrapheneOS install don't have it available. We reported it to them and I haven't checked the status of them fixing it. Several other apps had the same issue.

**Comment by thestinger** [comment]
You don't need to tell us what we already know: we know Chromium doesn't support the Android autofill API. That's what this feature request is about, but it should really be resolved upstream instead of with an invasive patch. Bromite doesn't have proper security updates at all, and a major reason why is how they approach things like this by adding tons of invasive patches. They also don't follow the right releases...

**Comment by thestinger** [comment]
We're making our own implementation of this feature.

**Comment by o-kotb** [comment]
Where can I find out more about this GrapheneOS implementation of autofill?
