### ISSUE TITLE
remove mremap from the syscall whitelist again, again

### ISSUE THREAD

**Issue by qua3k** [GrapheneOS/Vanadium#170]
There was a patch for this in the previous incarnation of GrapheneOS due to the replacement of the (jemalloc?) allocator with a port of OpenBSD malloc for arm64. Chrome has switched to PartitionAlloc on all platforms by intercepting all malloc requests with PartitionAlloc-Everywhere which means we can bring this back. This has been in Hexavalent for a while without any noted problems but we've recently began testing removing it from the renderer process without any problems as of yet.

**Comment by csagan5** [comment]
@qua3k the other 2 patches under [linux/](https://github.com/Hexavalent-Browser/Hexavalent/tree/main/patches/linux) do not have effects on Android, correct?

**Comment by qua3k** [comment]
They apply to Android but that's not going to be the approach taken by GrapheneOS to prevent dynamic code generation, which will likely involve SELinux transitions.

**Comment by qua3k** [comment]
I've also been working with Matt Denton of Google on getting this upstream; it's being tracked as crbug.com/1288042.

**Comment by csagan5** [comment]
That is fantastic news! I gave up upstreaming patches some time ago because the official tools took me quite some time to set up, I would otherwise have contributed a few small ones (and definitely not privacy/security-related, although @uazo might have some of that kind); never thought I could just drop a link like you did.

Sorry to continue the off-topic but: I am planning to include those patches under [linux/](https://github.com/Hexavalent-Browser/Hexavalent/tree/main/patches/linux) in Bromite, I am aware of the possibility of crashes that you are discussing there with Matt Denton.
I can try answering your question that you ask there about the switch/default: compiler will throw an error/warning when some case is not covered, perhaps that is the reason?

A more on-topic comment: `mremap` was introduced here: https://github.com/chromium/chromium/commit/d71e68da4fd871edaad91addf986bb0b40d6fdf8 (I am surprised that a security relaxing patch was greenlit in review with little resistance) but the referred safe browsing zip unpacking functionality is not used in Bromite/Vanadium.

**Comment by qua3k** [comment]
> compiler will throw an error/warning when some case is not covered, perhaps that is the reason?

No. They enumerated all the syscalls needed back when they first started working on the seccomp-bpf sandbox and initially allowed many of those syscalls before they had a sane seccomp policy. It's since been fixed and that code has largely been untouched for many years.

> I am surprised that a security relaxing patch was greenlit in review with little resistance

They aren't able to just refuse to relax the sandbox when mremap is used by many allocators as an efficient realloc. There wasn't any way around it and it's likely the same reason that Vanadium doesn't have this patch after GrapheneOS switched to hardened_malloc. It's not limited to the safe browsing zip functionality as realloc is used throughout the codebase.

**Comment by qua3k** [comment]
In case it wasn't clear before: we should remove `__NR_mremap` from `sandbox/linux/seccomp-bpf-helpers/baseline_policy_android.cc` as the fine grained seccomp filters for each process type aren't available on Android.

**Comment by csagan5** [comment]
> we should remove `__NR_mremap` from `sandbox/linux/seccomp-bpf-helpers/baseline_policy_android.cc` as the fine grained seccomp filters for each process type aren't available on Android.

I am going to test [this patch on Android](https://github.com/bromite/bromite/blob/5e4cd6c4ee7ac5db533f0278a1787ad6a7148405/build/patches/Remove-mremap-from-seccomp-baseline-policy.patch).
Meanwhile let's see what upstream will say in https://crbug.com/1288042.

**Comment by Zanthed** [comment]
pog
