### ISSUE TITLE
Add Brave Search

### ISSUE THREAD

**Issue by caveman1973** [GrapheneOS/Vanadium#171]
Brave Search is another search engine that respects privacy and gives good results.

search.brave.com

**Comment by Zanthed** [comment]
You can already add search engines to Vanadium. As long as it supports OpenSearch metadata you can add it yourself.

**Comment by caveman1973** [comment]
When I go to settings/search engines I don't see any other option. 

Can you tell me how to add a different one?

**Comment by Zanthed** [comment]
You need to open the search engine, make a search, then go to Settings -> Search engines and add it.

If it's not showing up, it doesn't support OpenSearch metadata.

**Comment by csagan5** [comment]
I think there are a couple upstream bugs that prevent the OpenSearch detection from working properly; you can see this because Firefox detects more search engine sites than Chromium derivatives.

I have fixed them in this Bromite patch: https://github.com/bromite/bromite/blob/100.0.4896.135/build/patches/OpenSearch-miscellaneous.patch and added more verbose logging to help understand what happens.

The bugs are:
* last visited time is a `0` UNIX timestamp first time the search engine is detected, thus it is never displayed on the recent engines list
* upon new visits to the search engine the logic to add it is skipped if the search engine was already parsed in the past, but the visit time is not updated
