### ISSUE TITLE
Support for PWA Share Target

### ISSUE THREAD

**Issue by retog** [GrapheneOS/Vanadium#289]
As PWAs can be distributed in a platform and store independent fashion, so they are an ideal fit for a free environemnt as grapheneOS. Unfortunately the support in Vanadium is currently very limited and PWAs are little more than bookmarks. 
The ability to register a share target is an important feature for a PWA to be a viable replacement for a native app.

I'm aware that google chrome and probably opera and samsung internet solve the issue with server-side compiled "WebAPKs" signed with the key of the Play Store, this is quite obviously not a solution for Vanadium and has already been discussed in #179.

However, it seems to be possible to implement a similar solution of PWA as Apps when accepting the following limitations:

- On installing a PWA the user must accept Vanadium to install an App from an Unknown Source
- The PWA does not share local-storage, indexedb and service worker with the site in Vanadium

The first limitation arguably increase security as it reduces the risk of the user accidentaly installing a malicious PWA that tricks the user into sharing data by mimicking a well known app. The second limitation reflects the user expectations on a full-fledged app.

So what would Vanadium have to do when installing a PWA?
- Compile the webapp as a new APK
- Generates a key-pair for the URI of the PWA and stores the keypair for future updates of the PWA
- Signes the APK with that key
- Hands over the APK to the OS the same way as when the user would have downloaded the APK from a website

**Comment by r3g-5z** [comment]
Not really sure this is feasible or in scope for this project. This should be an upstream feature request.

**Comment by ThatOneCalculator** [comment]
Chome (and I believe chromium?) already support this.

**Comment by r3g-5z** [comment]
If Chromium already supports this, then there's nothing for us to do. Either way, this feature request is overly complex and out of scope for this project and this isn't a "security feature".

**Comment by retog** [comment]
@ThatOneCalculator chrome has an APK signed using the play store key. This feature is required in the context of grapheneOS where one doesn't want to rely on Google online services.

**Comment by retog** [comment]
> If Chromium already supports this, then there's nothing for us to do. Either way, this feature request is overly complex and out of scope for this project and this isn't a "security feature".

It is a security feature in so far it allows PWA without the need of and the trust in Google services.

**Comment by r3g-5z** [comment]
That's not a security feature, that's an ideological motive. This project isn't about stripping every piece of "Google" out, especially for something so niche like this.

**Comment by r3g-5z** [comment]
You're more than welcome to implement this and contribute a clean patch yourself if you want it. We're not tracking this on our issue tracker and we're not going to work on this.

**Comment by retog** [comment]
> 

It's niche mainly because the big player prefer to have apps distributed via their app store and earn money and control from it. This is the only standardized and platform independent way of deploying application.

Currently Vanadium doesn't support the feature. If you think it's ok to use Google services then at least ad support for this. I think it would be better to doing it without Google services, but using the services from within Vanadium would be better than forcing the users to install Chrome for this feature.

**Comment by Wonderfall** [comment]
> Currently Vanadium doesn't support the feature. If you think it's ok to use Google services then at least ad support for this. 

Even that wouldn't be so trivial, though.

The problem is largely on Google: while the API is present in Chromium, the WebAPK minting server is [currently not available for other browsers than Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1243583). Given the current state of things, WebAPK is at the moment a proprietary service provided by Google rather than a standard that everyone can implement on their own.

It could be possible to reverse-engineer what the minting server does, but it would require more work from the project (plus additional maintenance costs). Even if it were possible to use Google's server, I don't think adding another dependency to yet another Google service would be desirable.

The best would be to wait for the Chromium team to come up for a propre solution, in my opinion. Then maybe Vanadium could have its own minting server?

**Comment by ThatOneCalculator** [comment]
I wonder if instead of a WebAPK, a TWA (trusted web app) could be used? They have pretty similar capabilities to WebAPKs, and iirc the creation process is open source

**Comment by retog** [comment]
@ThatOneCalculator I think TWA can be used to create an APK from a PWA. Similarly to what is described here: https://github.com/GoogleChromeLabs/bubblewrap/tree/main/packages/cli#bubblewrap-cli

I don't know if this is how /Twitter Lite/ is created. When installing /Twitter lite/ from the playstore the app is running in Vanadium and it provides a share target. Unlike the PWA installed from Vanadium it has however a rather ugly top bar.

**Comment by retog** [comment]
> It could be possible to reverse-engineer what the minting server does, but it would require more work from the project (plus additional maintenance costs). Even if it were possible to use Google's server, I don't think adding another dependency to yet another Google service would be desirable.

pwabuilder.com seems to be MIT-Licensed open source at https://github.com/pwa-builder/PWABuilder/tree/main/apps/pwabuilder. It provides the ability to create an APK out of an PWA. This APK uses TWA so that it will effectively run in Vanadium and also share local storage with Vanadium just as a PWA should. So it provides the functionality of the minting server.

**Comment by Wonderfall** [comment]
> > It could be possible to reverse-engineer what the minting server does, but it would require more work from the project (plus additional maintenance costs). Even if it were possible to use Google's server, I don't think adding another dependency to yet another Google service would be desirable.
> 
> pwabuilder.com seems to be MIT-Licensed open source at https://github.com/pwa-builder/PWABuilder/tree/main/apps/pwabuilder. It provides the ability to create an APK out of an PWA. This APK uses TWA so that it will effectively run in Vanadium and also share local storage with Vanadium just as a PWA should. So it provides the functionality of the minting server.

Yes, TWAs can be signed and published by developers, but those aren't exactly the same as WebAPKs. While both TWAs and WebAPKs should provide more or less the same level of functionality (there are very few differences aside from the installation process), implementing a local TWA builder is not the same as providing an adequate minting server to leverage what already exists in Chromium.

I understand this is something that you want but you have to understand it likely won't be in the roadmap of the project, especially since the Chromium team plans to address the issue.

**Comment by Wonderfall** [comment]
> @Wonderfall, the referenced PWA builder, is the code of an online service that creates APKs out of PWA, not a "local TWA builder". While it does not expose the API of the minting server, it provides its functionality.

It is the code of an online service powered by [Bubblewrap](https://github.com/GoogleChromeLabs/bubblewrap), which is what developers should use if they want to build and publish their own TWAs on Play Store (PWABuilder does that for you, online). But again, I think that is off-topic since while TWA/WebAPKs mainly differ by the way they're generated (also, TWA APKs are meant to be updated from Play Store, while Chrome attempts to update the WebAPK regularly), I don't think it would be a good idea to try to mimic what the minting server does.

> That TWA app don't work correctly when Vanadium is set as the default browser is another topic.

I haven't seen complaints about TWA apps not working correctly when installed from Play Store on GrapheneOS. If that is the case, this deserves its own issue indeed.

**Comment by lafleurdeboum** [comment]
Even if I share @retog's enthusiasm towards PWAs, I agree with @Wonderfall that if Chromium plans on fully implementing them then that could be enough - and having Chromium installed just for a few PWAs would still engage less code reproduction than a few Electron apps.

The Open Web Advocacy project is putting pressure on Google to have the keep their promess of opening the WebAPK minting to other browsers, filing complains in courts in EU, Japan and UK (their article [here]((https://open-web-advocacy.org/blog/google-must-share-the-ability-to-install-web-apps-in-android/) - found on [this Chrome thread](https://issues.chromium.org/issues/40195497)), so all hope is not lost for a future Chromium support.

Still, as a developer, this whole PWA infrastructure seems very fragile to me, and dependent on Google's good will, so I think I'll keep clear from PWAs. From my point of vue, frameworks like Electron or [Tauri](https://tauri.app) are far more reassuring.

I know this issue is closed, I just wanted to give those details on PWA status on Chromium for future readers. Hope I'm not necro-bumping ; the subject seems still hot to me.
