### ISSUE TITLE
[Feature Request] Implement Chromium User Profiles

### ISSUE THREAD

**Issue by russianbot91** [GrapheneOS/Vanadium#290]
On Chromium desktop it is possible to create multiple user profiles with separate settings/data that can be run concurrently. Would that be possible to add to Vanadium?

It would be good from a security standpoint because you could have one profile with JavaScript enabled for sites that need it and one with it disabled for everything else.

https://www.chromium.org/developers/creating-and-using-profiles/

**Comment by thestinger** [comment]
This is not planned since user and work profiles are provided by the OS, and future Android releases will provide cloned apps as a finer grained approach within profiles. It doesn't make sense to have an app specific implementation.

> It would be good from a security standpoint because you could have one profile with JavaScript enabled for sites that need it and one with it disabled for everything else.

You can already disable JavaScript globally and then enable it for the sites requiring it via the drop-down site details menu providing a shortcut for site settings.
