### ISSUE TITLE
Reaction to Web Integrity API (WEI)

### ISSUE THREAD

**Issue by solaslux** [GrapheneOS/Vanadium#345]
I refer to:
https://github.com/RupertBenWiser/Web-Environment-Integrity/blob/main/explainer.md

And can locate what appears to be the initial phase of its integration in chromium:

https://github.com/chromium/chromium/commit/6f47a22906b2899412e79a2727355efa9cc8f5bd#commitcomment-122743400

I am not familiar with Vanadium's planned development path, but this chromium development is alarming. 

Will Vanadium remove or otherwise mitigate the WEI?

**Comment by thestinger** [comment]
Vanadium is only available for GrapheneOS, which is not a Google certified Android OS and therefore is not going to pass checks for a Google Play certified OS. It's the web equivalent to the Play Integrity API, which detects GrapheneOS as a non-Google-certified OS and services requiring that aren't available. Android's hardware-based attestation system has support for alternate operating systems but in practice services only permit iOS and Google certified operating systems. The hardware-based attestation system has support for a pinning-based approach rather than only being able to weakly confirm that an central authority considers the OS certified. I doubt there will be support for validating alternate operating systems and browsers with this API in practice, since all the services using it are likely to require certification from Google, etc. Not really any point of us enabling it if it's never going to permit our OS or browser...

**Comment by notahomosapien** [comment]
Vanadium could disable the WebEnvironmentIntegrity feature like Brave [does](https://github.com/brave/brave-core/pull/19476/commits/4f9f7e36e3dd82dbeb611028a8aea5247ae77ec3), So it stays disabled even if the upstream enables it by default.
