### ISSUE TITLE
Freezing App

### ISSUE THREAD

**Issue by crueltekk** [GrapheneOS/Vanadium#68]
Some times vanadium hangs up if I have some more Tabs opened.
Opened tabs are sometimes around 15
Device: Pixel Coral
OS: Graphene
Build: QQ3A.200705.002.2020.07.06.20

**Comment by thestinger** [comment]
@crueltekk You'll need to provide more specific information, otherwise this is too generic to be an issue on the tracker. Instructions on how to reproduce it, logs from `adb logcat` and/or a captured bug report zip, etc. It's known that there are issues like CFI (Control Flow Integrity) violations in the upstream code that lead to problems so it's expected that there will be occasional issues.
