### ISSUE TITLE
The device name is leaked in the User Agent

### ISSUE THREAD

**Issue by resynth1943** [GrapheneOS/Vanadium#77]
This is a major privacy concern. Could we fix this? 
Bromite's user agent is as follows:

> Mozilla/5.0 (Linux; Android 9; Unspecified Device) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.0.0 Mobile Safari/537.36

Whereas Vanadium leaks my device name, as follows:

> Mozilla/5.0 (Linux; Android 10; Pixel 2 XL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.101 Mobile Safari/537.36

**Comment by thestinger** [comment]
That Bromite user agent is unique to Bromite. It advertises to every server that the connection is being made by Bromite. Do you see the problem with pursuing privacy by standing out from the crowd?

**Comment by resynth1943** [comment]
Right. I think I'm more comfortable with that, when compared to leaking the model and manufacturer of my device to every website I visit using Vanadium. Do as you wish, but I guess I'll have to use Bromite.

**Comment by thestinger** [comment]
There are far more users using Chrome on a Pixel 2 XL than Bromite or Vanadium users in total. You'll have less privacy with a more unique user agent. For a web site with JavaScript access, the device type is leaked via the huge amount of information available regardless. This is something that has to be addressed upstream rather than reducing the privacy of Vanadium users to make a feel good change that makes things worse.

**Comment by thestinger** [comment]
If you want changes that make you feel good rather than improving your privacy, I suggest not using GrapheneOS in general.

**Comment by resynth1943** [comment]
Honestly after what you said, I'm struggling to see why I should be using Chromium for privacy at all. I guess security (wow!!) is the main selling point?

**Comment by thestinger** [comment]
You'll have worse privacy with other browsers. You seem confused.

**Comment by resynth1943** [comment]
I think you're mixing up "fingerprinting" with not leaking my decide name to every website I visit.

**Comment by resynth1943** [comment]
> If you want changes that make you feel good rather than improving your privacy, I suggest not using GrapheneOS in general.

Condescending to others is a virtue.

Huh. So when Google launches their attack on user agent strings, I guess I'll have much better privacy using Bromite rather than Vanadium. 
![Screenshot_20200919-202433](https://user-images.githubusercontent.com/49915996/93687476-dd75ea00-faad-11ea-8c76-d70f0a32dccb.png)

**Comment by thestinger** [comment]
It's the device model, not the name, and removing it from the user agent downstream provides more information overall rather than less. Vanadium only runs on a few Pixel devices.

A website you visit can still check the screen resolution, detailed SoC information, performance characteristics and many other aspects that are highly tied to device model and enough to identify a Pixel 2 XL regardless. Removing it from the user agent won't hide it from the top level website you visited.

**Comment by resynth1943** [comment]
> A website you visit can still check the screen resolution, detailed SoC information, performance characteristics and many other aspects that are highly tied to device model and enough to identify a Pixel 2 XL regardless.

To be fair, that is going to be a lot harder. Are there any solutions that offer that?

Google has implemented this user-hostile information leaking to better their own Analytics product...

**Comment by resynth1943** [comment]
Also the above article I read makes for some interesting reading. It will close one of the information holes, but of course, as you yourself stated, there are many left to be patched.

From what I can see, Google are going to be freezing the user agent strings, and replace them with "Client Hints" that actually leak a lot more information. I'll have to do some reading on this one though.

I'll do some research and see how iOS stacks up to GrapheneOS, I'm sick of this Google bullshit.

**Comment by thestinger** [comment]
> Huh. So when Google launches their attack on user agent strings, I guess I'll have much better privacy using Bromite rather than Vanadium.

You seem to be misunderstanding those changes, and I'm not sure how it's relevant to the conclusion you seem to be drawing. The fact is that changing the user agent in any way will reduce the privacy of our users, so we're not going to do it. This has to be addressed upstream or not at all since we don't want the HTTP connections made by the WebView or browser to be identifiable as coming from Vanadium. The BUILD_ID used to be included in the user agent and was already removed upstream. It's still included for the WebView due to CDD/CTS requirements that are slower to change than Chromium. Similar to this, we couldn't simply remove it without giving up completely on blending in with the crowd to any extent at all. Every single HTTP request from Bromite is identifiable as coming from Bromite. Vanadium is used on a small set of devices so making the user agent unique to Vanadium would already leak that you use one of those few devices models.

**Comment by thestinger** [comment]
Device model can also be obtained by the website for iOS and it's far easier since there are far fewer device models to differentiate. Fewer device models is a good thing though, because users blend in better with far more users on the same device models.

**Comment by resynth1943** [comment]
> The fact is that changing the user agent in any way will reduce the privacy of our users, so we're not going to do it.

Hmm, it seems this isn't as simple as I first assumed. What a mess.

> The fact is that changing the user agent in any way will reduce the privacy of our users, so we're not going to do it.

To be fair, that won't be the case when Client Hints come in, although that's going to be even harder to fix, from what I understand.

> Device model can also be obtained by the website for iOS and it's far easier since there are far fewer device models to differentiate. Fewer device models is a good thing though, because users blend in better with far more users on the same device models.

Oh sick. I'll try and stick my head into the off-topic room and see what other people think about it. 

Thanks for the pearls of knowledge, Daniel. This leaves me with a lot to think about.

**Comment by thestinger** [comment]
If you're okay with being identified as using Vanadium, you're implying that you're okay with being identified as using one of the 8 currently supported device models for GrapheneOS and therefore Vanadium. The specific model can be easily determined via screen resolution and performance. What's the point in reducing privacy just to feel good about something? It doesn't make sense. That's not how we do development. There's a big difference between being able to determine that the browser is Vanadium with full JavaScript access (we currently don't do anything that deviates from what is possible with a configuration of Chromium - but we do change settings not exposed in the UI) vs. from the user agent in every single HTTP request. We really don't want every HTTP request from Vanadium to advertise itself as Vanadium so we need to match a standard user agent for the browser engine it's based on.

**Comment by thestinger** [comment]
Similar to how upstream was convinced not to include BUILD_ID, it may be possible to convince them not to include the device model. The argument does not need to be solely based on privacy. Including the device model leads to worse web compatibility since developers hard-wire support for only mainstream devices and provide a worse experience on devices that are not included in their checks. The browser should be exposing capabilities, etc. to web sites rather than having web developers hard-wire anything based on device model.

Client hints isn't really going to leak any more information. However, it would be nice if they didn't include information that should not be in the user agent in the first place, such as device model and browser version. Web developers should detect features, bugs, etc. rather than hard-wiring support for specific browsers and versions.

**Comment by resynth1943** [comment]
> Similar to how upstream was convinced not to include BUILD_ID, it may be possible to convince them not to include the device model.

Ahh yes. I'm definitely going to convince a company that sells a product that detects this (Analytics) to break that. I feel like I'm between a rock and a hard place... 

To be honest, I don't see an obvious reason as to why webmasters must know the device models of their visitors, but heyho.

> The browser should be exposing capabilities, etc. to web sites rather than having web developers hard-wire anything based on device model.

Agreed. Browser sniffing is a terrible practice. If I'm not mistaken, the main argument behind dropping User Agents was browser sniffing, so I guess it's time to replace that with something that opens up even more information ...?

It's disappointing to know that these big companies are basically in control of this whole fingerprinting debacle.

I may just get an older phone, like a Walkman, or perhaps invest in iOS. I'd love to talk to you about that, sometime :D

**Comment by thestinger** [comment]
> that opens up even more information ...?

It doesn't provide any new information that's not already available.

**Comment by csagan5** [comment]
> That Bromite user agent is unique to Bromite. It advertises to every server that the connection is being made by Bromite. Do you see the problem with pursuing privacy by standing out from the crowd?

It is working as intended; see https://github.com/bromite/bromite/issues/483

Bromite was previously using a fixed device model; back then when [issue 483](https://github.com/bromite/bromite/issues/483) was closed, upstream was going to freeze the user agent before v85, but this never materialised.

Rather than going back to the previous approach I decided to stick to the (future) upstream feature here.

> We really don't want every HTTP request from Vanadium to advertise itself as Vanadium so we need to match a standard user agent for the browser engine it's based on.

@thestinger what type of privacy violation can happen when a third-party knows that the browser is Vanadium instead of Chrome (aside from the disclosure of the browser preference itself)? I am interested in what we are modelling here as the malicious actor. I have thought of using the information to check for specific vulnerabilities, profiling with the goal of adding to watch lists, denying access (or modifying the results of a web page), fingerprinting. None of them holds water for me.

**Comment by thestinger** [comment]
Vanadium hardly has any users compared to Chromium variants in general. It also only runs on 8 device models. Leaking that the user is using Vanadium leaks far more information than providing the device model like the unaltered browser.

**Comment by thestinger** [comment]
Hiding information like this when JavaScript is enabled is a hopeless and misguided cause where people mislead themselves about what is being accomplished but leaking that the browser is Vanadium in HTTP headers is something that we can easily avoid and will definitely choose to avoid.

I already wrote more in-depth responses in the comments above. It's a requirement to read the thread before responding.

**Comment by thestinger** [comment]
Simple question: what leaks more information about you, that you use Vanadium on one of the 8 supported device models (which can be differentiated in multiple ways including screen resolution) or that you use a specific one of those device models? The answer is quite straightforward and obvious: leaking that the user uses Vanadium provides far more information. That's why this issue is closed, and comparable issues would also be closed.

Leaking that the user uses Vanadium in the HTTP headers is much worse than blending in with every user on a widely used Android device. Pixels are the most popular specific Android device models in North America. Unfortunately, we can't hide that the user is using Vanadium to JavaScript, but we can't hide the device model either since they are easily differentiated from each other. No point in playing privacy theatre games with that.

Appearing to be Chrome on the stock OS to anything without JavaScript access is a goal of Vanadium. JavaScript makes all of this hopeless due to the scope of the APIs and the ability to do performance-based fingerprinting. It's straightforward to identify Chrome on GrapheneOS vs. Chrome on the stock OS by measuring the throughput of one of the few APIs significantly slowed down by the OS hardening vs. the majority of APIs with little to no impact. It's not something we can hide. Vanadium's hardening can similarly be detected like that. The same approach can identify the SoC and many other properties of devices. This can be made quite reliable, and can be done very quickly. I have a very basic Qualcomm SoC family detector as a proof of concept. When you combine that with screen resolutions, GPU profiling and everything else... it's a bit silly to pretend that the information is hidden. Something I can bypass in a day of work myself with no experience working on that kind of tracking code is privacy theatre.

What is the argument to leak that the user is using Vanadium on one of the 8 supported devices instead of blending in with the millions of users on one of those devices? There are clearly far more than 8x as many people using Chrome on the stock OS than Vanadium. It's a massive difference.

We have discussed exactly this in depth in the past and the decision was made that we need to follow upstream on this. The same approach was taken for BUILD_ID, which we encouraged them to remove, and eventually they actually did end up removing it. Have not made an attempt to push on this issue yet, and it would be harder, but it is a political problem with a political solution (and I have plans on how to deal with that, as I talked about above) rather than a technical problem that we can solve ourselves. A "solution" downstream just makes things worse for us.

**Comment by resynth1943** [comment]
> Have not made an attempt to push on this issue yet, and it would be harder, but it is a political problem with a political solution (and I have plans on how to deal with that, as I talked about above) rather than a technical problem that we can solve ourselves.

Please do!

**Comment by csagan5** [comment]
> I already wrote more in-depth responses in the comments above. It's a requirement to read the thread before responding.

I had already read the thread; none of the previous comments are answering my question though, feel free to quote the snippets which do.

All that I understood is that you give some value to being not unique from HTTP headers point of view, while you acknowledge that it is impossible through Javascript; since their use conflates to the same actor*, I fail to reckon the importance of the former.

*= I am not considering users which regularly disable Javascript while browsing

Your last comment is still answering the original post though, but I am not asking to change Vanadium user agent. There can be multiple ways to handle this correctly, or a single way, or no way; without more information about the type of privacy violation one wants to harden against, I cannot assess this.

(Reporting my question again to save readers' some scrolling):
> what type of privacy violation can happen when a third-party knows that the browser is Vanadium instead of Chrome (aside from the disclosure of the browser preference itself)? I am interested in what we are modelling here as the malicious actor. I have thought of using the information to check for specific vulnerabilities, profiling with the goal of adding to watch lists, denying access (or modifying the results of a web page), fingerprinting. None of them holds water for me.

**Comment by thestinger** [comment]
> since their use conflates to the same actor

It doesn't conflate to the same thing, and the device model is leaked with JavaScript access regardless.

**Comment by csagan5** [comment]
> the device model is leaked with JavaScript access regardless.

We agree there; it is also possible to identify the chipset by looking at the WebGL capabilities, see [my comment here](https://github.com/Eloston/ungoogled-chromium/issues/429#issuecomment-422265119) where I sustain that it is pointless to hide the WebGL vendor and renderer for pretty much the same reasons as yours.

> It doesn't conflate to the same thing

This is where we disagree; since most users have Javascript enabled and HTTP calls reporting back to the server client-side capabilities are the norm, I consider this information (the HTTP headers information and the Javascript-sourced information) collected by the same actors (for analytics or whichever other purpose).

My intent is not to "throw the baby out with the bathwater" but I really want to understand the reasoning; I have an intent to start to document all decisions behind patches used in Bromite; for example when I added a [patch of yours](https://github.com/bromite/bromite/blob/85.0.4183.82/build/patches/Enable-fwrapv-in-Clang-for-non-UBSan-builds.patch) I have added your explanation as well. I think this should be followed through for all patches/changes so that anytime, anyone can read and understand the context of each. You can see my questions as part of this effort; I think it is a good practice for any open source project, as it helps maintain the "openness" aspect by documenting the choices and leaves little room for privacy theatre games and hand-waving.

**Comment by thestinger** [comment]
For example, many sites include images from other sites but don't trust those sites with the ability to run arbitrary JavaScript. Not everything is the top-level origin. Disabling JavaScript and enabling it only on specific sites is also a valid, supported option and has gotten better support upstream fairly recently. It's more usable than it used to be.

**Comment by thestinger** [comment]
It would be useful to keep an eye on the % of browsers with the frozen user agent. It's possible that Google will deploy this as a testing experiment since it's a flag that could be changed as part of those variations. We can adopt this once it's used for ~10% of more of Chrome users.

**Comment by csagan5** [comment]
> We can adopt this once it's used for ~10% of more of Chrome users.

Bromite ships with adblock filters enabled by default, and by such filters alone (updated bi-weekly) it is possible to identify it. Additional default options can contribute to identify it with more precision; does Vanadium have an explicit goal to always be identical to Chrome at all times from "signals" perspective? If yes, my next question would be: have you thought of adding some automated tests to safeguard this goal and prevent regressions?

**Comment by thestinger** [comment]
> does Vanadium have an explicit goal to always be identical to Chrome at all times from "signals" perspective?

When JavaScript is disabled, that would be nice. Changing user-facing configuration defaults doesn't count, but changing the values of flags that are not changed by most users is somewhat different. If this setting was exposed in the normal settings by Chrome we'd definitely be enabling it.

There is at least one other change currently conflicting with this (hyperlink auditing), but it isn't an excuse to add more changes like it.

**Comment by thestinger** [comment]
They still haven't started rolling this out, even as an experiment. However, there's progress on the issue.

**Comment by thestinger** [comment]
I've decided that we're ready to enable this based on statistics from our own web site. A problem we've noticed is that there are some minor configuration differences between Chromium and Chrome which we don't want to invest effort into resolving because it's going to be obsoleted by this anyway. I don't think this is really a step forward right now, but there's a lot that needs to be done upstream before there's any real hope of avoiding fingerprinting anyway. I don't see much harm in enabling this a bit prematurely right now.

**Comment by thestinger** [comment]
For example, I don't really understand why Chrome already uses the frozen armv8l string rather than aarch64 without the user agent freeze enabled. It seems like they must configure the build or something else a bit differently. There are some other differences visible without JavaScript too. Field trials are one of the issues, since they've got various things enabled across portions or even the whole userbase which we don't have turned on right now. I think we need to find a way of getting their field trial deployment information. If something has 100% deployment then that basically means it's enabled by default, so we're not matching everything.

**Comment by csagan5** [comment]
See https://bugs.chromium.org/p/chromium/issues/detail?id=1078270

It was introduced on purpose here: https://github.com/chromium/chromium/commit/0585bc93a421ad5fe1699619980350bee6678a5d

> I think we need to find a way of getting their field trial deployment information

I assume you mean the information returned by their servers, and not the one embedded via JSON about default field trials. You should be able to find the code that does that in https://github.com/chromium/chromium/blob/88.0.4324.207/components/variations/service/variations_service.cc

However I see they have introduced the concept of entropy in there, so I do not fully grasp anymore how it works.

**Comment by thestinger** [comment]
Chrome 88 uses armv8l but Chromium ends up using aarch64.

**Comment by thestinger** [comment]
Chrome 88 uses armv8l but Chromium ends up using aarch64 at least without field trials enabled. I haven't tried with them enables. I don't really see the answer to why there's a difference there.
