### ISSUE TITLE
Vanadium System WebView tries to access clientservices.googleapis.com in the background

### ISSUE THREAD

**Issue by ericschdt** [GrapheneOS/Vanadium#89]
Version: RQ1A.201205.008.2020.12.08.08
Component: org.grapheneos.vanadium.webview

I do not use the Vanadium System WebView actively, however NetGuard revealed that it tries to contact `clientservices.googleapis.com` in the background:
![Screenshot_20201210-115527](https://user-images.githubusercontent.com/43318127/101764726-4af74c80-3ad8-11eb-8535-ee2497d6798b.png)

Why does it try to access this URL? I doubt it should do let alone for privacy reasons and especially not on GrapheneOS.

**Comment by thestinger** [comment]
> I do not use the Vanadium System WebView actively

What makes you think that you aren't actively using the WebView? It's not a user-facing app but rather a library. It exists to provide the WebView for other apps. Other apps control instances of it that they use to render web content. The WebView's own app context is used to provide support for those apps and developer tools.

> however NetGuard revealed that it tries to contact clientservices.googleapis.com in the background:

Apps make connections on behalf of others. You cannot reliably attribute the source of a connection to an app like this.

> Why does it try to access this URL? I doubt it should do let alone for privacy reasons and especially not on GrapheneOS.

Fetching a variations seed on behalf of apps using the WebView. You can see from the commits to the Vanadium project that we're gradually disabling this kind of functionality. We already disabled this for the Vanadium browser, but the WebView has support for handling it on behalf of apps and it needs to be disabled separately.

**Comment by thestinger** [comment]
It should be addressed by https://github.com/GrapheneOS/Vanadium/blob/11/patches/0075-disable-WebView-variations-support.patch. If you're interested in testing it, there will be a new release ready soon. In order to properly test it, you should clear the app data for the Vanadium WebView, reboot, and then launch one of your apps that uses the WebView in a way that triggers this.

**Comment by thestinger** [comment]
@ericschdt You can install the latest release of TrichromeWebview.apk from https://github.com/GrapheneOS/platform_external_vanadium/tree/11/prebuilt/arm64. This is signed with the same key as the application distributed with the OS so it can be installed as an update to it.

The library, browser and WebView apks need to be kept in sync. We've only changed the WebView. You may need to clear the app data and reboot in order for the update to fully kick in due to not updating the version code for this change, since we won't actually be shipping it like this.

**Comment by ericschdt** [comment]
>  If you're interested in testing it

Thanks, I may look into it during the weekend when I find some more time!

**Comment by thestinger** [comment]
Should be fixed by the latest release. Can reopen the issue if it's still a problem.
