### ISSUE TITLE
Add a View Source item to the 3 dot menu

### ISSUE THREAD

**Issue by mrhebisan** [GrapheneOS/Vanadium#97]
I wanted to view the source of a website and went to find the View Source option.  It seems to be missing.  It is something implemented in Bromite, which is nice of them to offer.  See screenshots for comparison.  In Bromite it is between "Add to Homescreen" and "Desktop Site"

Would you consider adding a view source option to the 3 dot menu?

**Vanadium**

![Screenshot_20210207-121009_1](https://user-images.githubusercontent.com/78703114/107158404-8da19d80-693e-11eb-90e8-beeb86b40ab4.png)

**Bromite**

![Screenshot_20210207-121101](https://user-images.githubusercontent.com/78703114/107158364-592de180-693e-11eb-8032-049f4bbb90bd.png)

**Comment by thestinger** [comment]
You can use `view-source:`. It's a developer feature and I don't think those should be in the normal menus without activating a developer mode. It's not something we're interested in implementing downstream.

**Comment by thestinger** [comment]
i.e. if you're at `https://example.com/` change it to `view-source:https://example.com/`. It's not usually particularly useful since it's not the fancy source viewer in the developer tools with pretty printing and proper browsing of the code. So, for example, you're on grapheneos.org and everything that's deployed is minified. It's not going to be readable. You should view it in https://github.com/GrapheneOS/grapheneos.org.

The actual developer tools have to be used via Chromium on a desktop via adb because they don't have the UI implemented via mobile. Definitely not something we want to implement ourselves downstream. It would be nice if Chromium provided that stuff with the developer mode, but we won't do it.

There's a mobile Chromium developer mode activated in a similar way as the AOSP developer mode. It's incredibly barebones right now though.

**Comment by mrhebisan** [comment]
Thank you for the information regarding how to access this view.  While a menu item would be nice, it's good to know that the option exists in some form.
